### Создание проекта
POST http://192.168.0.14:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:a23db9e2-a77e-4690-8e95-fb9a606a9144

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name",
  "id": "id",
  "copyAllAssociatedSettings": true
}

### Генерация токена
GET http://admin:admin@192.168.0.14:8111/authenticationTest.html?csrf
Accept: application/json
Authorization: Basic admin admin

#### Создание builde configuration
POST http://admin:admin@192.168.0.14:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:a23db9e2-a77e-4690-8e95-fb9a606a9144

{
  "id": "id",
  "name": "Print hello world",
  "project": {
    "id": "id"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

#### Run builde
POST http://admin:admin@192.168.0.14:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:a23db9e2-a77e-4690-8e95-fb9a606a9144

{
  "buildType": {
    "id": "id"
  }
}

#### Check builde status
GET http://admin:admin@192.168.0.14:8111/app/rest/builds/id:2
Content-Type: application/json
Accept: application/json
X-T-CSRF-Token:a23db9e2-a77e-4690-8e95-fb9a606a9144

### getRrequest
GET http://admin:admin@192.168.0.14:8111/app/rest/buildTypes/id:id
Accept: application/json

### Set authentication settings
PUT http://admin:admin@192.168.0.14:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:114bf213-0636-4c46-b1ef-3349f38c7fda

{
  "allowGuest": true,
  "guestUsername": "string",
  "welcomeText": "string",
  "collapseLoginForm": true,
  "perProjectPermissions": true,
  "emailVerification": true,
  "modules": {
    "module": [
      {
        "name": "string",
        "properties": {
          "property": [
            {
              "name": "string",
              "value": "string",
              "inherited": true,
              "type": {
                "rawValue": "string"
              }
            }
          ],
          "count": 0,
          "href": "string"
        }
      }
    ]
  }
}